"""The result of :meth:`saccade.Video.ask`."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Literal

from saccade.models.context import Evidence
from saccade.models.frame import Frame


@dataclass(frozen=True, slots=True)
class Answer:
    """An LLM's answer plus exactly what it was shown.

    ``text`` is generated by your LLM. ``evidence`` and ``frames`` are the source material
    Saccade sent with the question — timestamps there come from the video, not the LLM.

    Attributes:
        question: What was asked.
        text: The LLM's answer.
        evidence: Transcript segments and frames that were sent, with source timestamps.
        frames: The images that were sent.
        mode: ``"full"`` (whole transcript sent) or ``"retrieved"`` (relevant passages only).
        model: Model name reported by the endpoint.
        usage: Token usage reported by the endpoint.
    """

    question: str
    text: str
    evidence: list[Evidence]
    frames: list[Frame]
    mode: Literal["full", "retrieved"]
    model: str | None = None
    usage: dict[str, Any] = field(default_factory=dict)

    @property
    def input_tokens(self) -> int | None:
        """Prompt tokens billed by the endpoint (transcript, images, instructions)."""
        return _usage(self.usage, "prompt_tokens", "input_tokens")

    @property
    def output_tokens(self) -> int | None:
        """Completion tokens billed by the endpoint, including hidden reasoning."""
        return _usage(self.usage, "completion_tokens", "output_tokens")

    @property
    def total_tokens(self) -> int | None:
        total = _usage(self.usage, "total_tokens")
        if total is None and self.input_tokens is not None and self.output_tokens is not None:
            return self.input_tokens + self.output_tokens
        return total

    def to_dict(self) -> dict[str, Any]:
        return {
            "question": self.question,
            "text": self.text,
            "mode": self.mode,
            "model": self.model,
            "usage": self.usage,
            "evidence": [e.to_dict() for e in self.evidence],
            "frames": [f.to_dict() for f in self.frames],
        }

    def to_json(self, *, indent: int | None = 2) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent)

    def __str__(self) -> str:
        return self.text


def _usage(usage: dict[str, Any], *keys: str) -> int | None:
    for key in keys:
        value = usage.get(key)
        if isinstance(value, int):
            return value
    return None
